name: Bingo
description:  Bingo Plugin by Zarg
version: 2.1.2
author: Zarg
api-version: 1.13

main: de.synex.bingo.main.Main

commands:
  bingopl:
    description: Standard Command
    usage: /bingopl
  bingorestart:
    description: Startet das Spiel manuell neu
    usage: /restart
  top:
    description: An die Oberflaeche teleportieren
    usage: /top
  bingo:
    description: Oeffnet das Bingo Menu
    usage: /bingo <start/restart>
    aliases: b
  start:
    description: force Start
    usage: /start
  brestart:
    description: force restart
    usage: /brestart 
  teams:
    description: Team Choice
    usage: /teams 
  settings:
    description: Set the Settings of Bingo
    usage: /settings 
permissions:
  bingo.defaultcmd:
    description: Standard Command
    default: true
  bingo.restart:
    description: Manuelles Neustarten
    default: op
  bingo.top:
    description:
    default: true
  bingo.gamemaster:
    description:
    default: op
  bingo.start:
    description:
    default: op