// 
// Decompiled by Procyon v0.5.36
// 

package de.synex.bingo.util;

import org.bukkit.ChatColor;
import org.bukkit.configuration.file.YamlConfiguration;

import java.io.File;

import org.bukkit.configuration.file.FileConfiguration;
import de.synex.bingo.main.Main;

public class ConfigLink {
    Main main;
    FileConfiguration language;
    public String prefix;
    public String pluginstarted;
    public String pluginstopped;
    public String kickmsgwinOnePlayer;
    public String kickmsgwinTwoPlayer;
    public String FollowingTeamTeleported;
    public String T1OnePlayer;
    public String T1TwoPlayer;
    public String T2OnePlayer;
    public String T2TwoPlayer;
    public String T3OnePlayer;
    public String T3TwoPlayer;
    public String T4OnePlayer;
    public String T4TwoPlayer;
    public String T5OnePlayer;
    public String T5TwoPlayer;
    public String T6OnePlayer;
    public String T6TwoPlayer;
    public String T7OnePlayer;
    public String T7TwoPlayer;
    public String T8OnePlayer;
    public String T8TwoPlayer;
    public String T9OnePlayer;
    public String T9TwoPlayer;
    public String BoatName;
    public String StartMessage;
    public String ActionBar;
    public String nopermission;
    public String notavailable;
    public String gamewillstart;
    public String gamestartsin;
    public String gamestarts;
    public String gamealreadystarts;
    public String usagebingopl;
    public String noconsole;
    public String usagebingorestart;
    public String teleportedtop;
    public String teleportedworld;
    public String mustbingoworld;
    public String nospectatortop;
    public String usagetop;
    public String bingoitemsinround;
    public String teamfounditemTeam1;
    public String teamfounditemTeam2;
    public String teamfounditemTeam3;
    public String teamfounditemTeam4;
    public String teamfounditemTeam5;
    public String teamfounditemTeam6;
    public String teamfounditemTeam7;
    public String teamfounditemTeam8;
    public String teamfounditemTeam9;
    public String yourteamfoundfollowingitemsalready;
    public String onlyingamecommand;
    public String usagebingo;
    public String usagebrestart;
    public String teamselectorInventoryTitle;
    public String teamselection;
    public String tablistheaderingame;
    public String tablistheaderlobby;
    public String tablistfooter;
    public String spectatorjoined;
    public String lobbyisfullkick;
    public String playerjoined;
    public String roundisrestartingkick;
    public String jointeam1;
    public String alreadyteam1;
    public String team1full;
    public String jointeam2;
    public String alreadyteam2;
    public String team2full;
    public String jointeam3;
    public String alreadyteam3;
    public String team3full;
    public String jointeam4;
    public String alreadyteam4;
    public String team4full;
    public String jointeam5;
    public String alreadyteam5;
    public String team5full;
    public String jointeam6;
    public String alreadyteam6;
    public String team6full;
    public String jointeam7;
    public String alreadyteam7;
    public String team7full;
    public String jointeam8;
    public String alreadyteam8;
    public String team8full;
    public String jointeam9;
    public String alreadyteam9;
    public String team9full;
    public String TablistTeam1Colour;
    public String TablistTeam2Colour;
    public String TablistTeam3Colour;
    public String TablistTeam4Colour;
    public String TablistTeam5Colour;
    public String TablistTeam6Colour;
    public String TablistTeam7Colour;
    public String TablistTeam8Colour;
    public String TablistTeam9Colour;
    public String TablistDefaultUserColour;
    public String TablistGamemasterColour;
    public String deathmessage;
    public String leftserveringame;
    public String leftserveringamespectator;
    public String leftserverlobby;
    public String gameisrestarting;
    public String chatformatTeam1;
    public String chatformatTeam2;
    public String chatformatTeam3;
    public String chatformatTeam4;
    public String chatformatTeam5;
    public String chatformatTeam6;
    public String chatformatTeam7;
    public String chatformatTeam8;
    public String chatformatTeam9;
    public String chatformatwithoutteam;
    public String chatcolourDefaultUser;
    public String chatcolourGamemaster;
    public String scoreboardTitle;
    public String scoreboardYourTeam;
    public String scoreboardTeam1;
    public String scoreboardTeam2;
    public String scoreboardTeam3;
    public String scoreboardTeam4;
    public String scoreboardTeam5;
    public String scoreboardTeam6;
    public String scoreboardTeam7;
    public String scoreboardTeam8;
    public String scoreboardTeam9;
    public String scoreboardNoTeam;
    public String usagestart;

    public ConfigLink(final Main pl) {
        this.language = (FileConfiguration) YamlConfiguration.loadConfiguration(new File("plugins/Bingo", "language.yml"));
        this.prefix = ChatColor.translateAlternateColorCodes('&', this.language.getString("prefix"));
        this.pluginstarted = ChatColor.translateAlternateColorCodes('&', this.language.getString("pluginstarted"));
        this.pluginstopped = ChatColor.translateAlternateColorCodes('&', this.language.getString("pluginstopped"));
        this.kickmsgwinOnePlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("kickmsgwinOnePlayer"));
        this.kickmsgwinTwoPlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("kickmsgwinTwoPlayer"));
        this.FollowingTeamTeleported = ChatColor.translateAlternateColorCodes('&', this.language.getString("FollowingTeamTeleported"));
        this.T1OnePlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("T1OnePlayer"));
        this.T1TwoPlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("T1TwoPlayer"));
        this.T2OnePlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("T2OnePlayer"));
        this.T2TwoPlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("T2TwoPlayer"));
        this.T3OnePlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("T3OnePlayer"));
        this.T3TwoPlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("T3TwoPlayer"));
        this.T4OnePlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("T4OnePlayer"));
        this.T4TwoPlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("T4TwoPlayer"));
        this.T5OnePlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("T5OnePlayer"));
        this.T5TwoPlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("T5TwoPlayer"));
        this.T6OnePlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("T6OnePlayer"));
        this.T6TwoPlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("T6TwoPlayer"));
        this.T7OnePlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("T7OnePlayer"));
        this.T7TwoPlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("T7TwoPlayer"));
        this.T8OnePlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("T8OnePlayer"));
        this.T8TwoPlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("T8TwoPlayer"));
        this.T9OnePlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("T9OnePlayer"));
        this.T9TwoPlayer = ChatColor.translateAlternateColorCodes('&', this.language.getString("T9TwoPlayer"));
        this.BoatName = ChatColor.translateAlternateColorCodes('&', this.language.getString("BoatName"));
        this.StartMessage = ChatColor.translateAlternateColorCodes('&', this.language.getString("StartMessage"));
        this.ActionBar = ChatColor.translateAlternateColorCodes('&', this.language.getString("ActionBar"));
        this.nopermission = ChatColor.translateAlternateColorCodes('&', this.language.getString("nopermission"));
        this.notavailable = ChatColor.translateAlternateColorCodes('&', this.language.getString("notavailable"));
        this.gamewillstart = ChatColor.translateAlternateColorCodes('&', this.language.getString("gamewillstart"));
        this.gamestartsin = ChatColor.translateAlternateColorCodes('&', this.language.getString("gamestartsin"));
        this.gamestarts = ChatColor.translateAlternateColorCodes('&', this.language.getString("gamestarts"));
        this.gamealreadystarts = ChatColor.translateAlternateColorCodes('&', this.language.getString("gamealreadystarts"));
        this.usagebingopl = ChatColor.translateAlternateColorCodes('&', this.language.getString("usagebingopl"));
        this.noconsole = ChatColor.translateAlternateColorCodes('&', this.language.getString("noconsole"));
        this.usagebingorestart = ChatColor.translateAlternateColorCodes('&', this.language.getString("usagebingorestart"));
        this.teleportedtop = ChatColor.translateAlternateColorCodes('&', this.language.getString("teleportedtop"));
        this.teleportedworld = ChatColor.translateAlternateColorCodes('&', this.language.getString("teleportedworld"));
        this.mustbingoworld = ChatColor.translateAlternateColorCodes('&', this.language.getString("mustbingoworld"));
        this.nospectatortop = ChatColor.translateAlternateColorCodes('&', this.language.getString("nospectatortop"));
        this.usagetop = ChatColor.translateAlternateColorCodes('&', this.language.getString("usagetop"));
        this.bingoitemsinround = ChatColor.translateAlternateColorCodes('&', this.language.getString("bingoitemsinround"));
        this.teamfounditemTeam1 = ChatColor.translateAlternateColorCodes('&', this.language.getString("teamfounditemTeam1"));
        this.teamfounditemTeam2 = ChatColor.translateAlternateColorCodes('&', this.language.getString("teamfounditemTeam2"));
        this.teamfounditemTeam3 = ChatColor.translateAlternateColorCodes('&', this.language.getString("teamfounditemTeam3"));
        this.teamfounditemTeam4 = ChatColor.translateAlternateColorCodes('&', this.language.getString("teamfounditemTeam4"));
        this.teamfounditemTeam5 = ChatColor.translateAlternateColorCodes('&', this.language.getString("teamfounditemTeam5"));
        this.teamfounditemTeam6 = ChatColor.translateAlternateColorCodes('&', this.language.getString("teamfounditemTeam6"));
        this.teamfounditemTeam7 = ChatColor.translateAlternateColorCodes('&', this.language.getString("teamfounditemTeam7"));
        this.teamfounditemTeam8 = ChatColor.translateAlternateColorCodes('&', this.language.getString("teamfounditemTeam8"));
        this.teamfounditemTeam9 = ChatColor.translateAlternateColorCodes('&', this.language.getString("teamfounditemTeam9"));
        this.yourteamfoundfollowingitemsalready = ChatColor.translateAlternateColorCodes('&', this.language.getString("yourteamfoundfollowingitemsalready"));
        this.onlyingamecommand = ChatColor.translateAlternateColorCodes('&', this.language.getString("onlyingamecommand"));
        this.usagebingo = ChatColor.translateAlternateColorCodes('&', this.language.getString("usagebingo"));
        this.usagebrestart = ChatColor.translateAlternateColorCodes('&', this.language.getString("usagebrestart"));
        this.teamselectorInventoryTitle = ChatColor.translateAlternateColorCodes('&', this.language.getString("teamselectorInventoryTitle"));
        this.teamselection = ChatColor.translateAlternateColorCodes('&', this.language.getString("teamselection"));
        this.tablistheaderingame = ChatColor.translateAlternateColorCodes('&', this.language.getString("tablistheaderingame"));
        this.tablistheaderlobby = ChatColor.translateAlternateColorCodes('&', this.language.getString("tablistheaderlobby"));
        this.tablistfooter = ChatColor.translateAlternateColorCodes('&', this.language.getString("tablistfooter"));
        this.spectatorjoined = ChatColor.translateAlternateColorCodes('&', this.language.getString("spectatorjoined"));
        this.lobbyisfullkick = ChatColor.translateAlternateColorCodes('&', this.language.getString("lobbyisfullkick"));
        this.playerjoined = ChatColor.translateAlternateColorCodes('&', this.language.getString("playerjoined"));
        this.roundisrestartingkick = ChatColor.translateAlternateColorCodes('&', this.language.getString("roundisrestartingkick"));
        this.jointeam1 = ChatColor.translateAlternateColorCodes('&', this.language.getString("jointeam1"));
        this.alreadyteam1 = ChatColor.translateAlternateColorCodes('&', this.language.getString("alreadyteam1"));
        this.team1full = ChatColor.translateAlternateColorCodes('&', this.language.getString("team1full"));
        this.jointeam2 = ChatColor.translateAlternateColorCodes('&', this.language.getString("jointeam2"));
        this.alreadyteam2 = ChatColor.translateAlternateColorCodes('&', this.language.getString("alreadyteam2"));
        this.team2full = ChatColor.translateAlternateColorCodes('&', this.language.getString("team2full"));
        this.jointeam3 = ChatColor.translateAlternateColorCodes('&', this.language.getString("jointeam3"));
        this.alreadyteam3 = ChatColor.translateAlternateColorCodes('&', this.language.getString("alreadyteam3"));
        this.team3full = ChatColor.translateAlternateColorCodes('&', this.language.getString("team3full"));
        this.jointeam4 = ChatColor.translateAlternateColorCodes('&', this.language.getString("jointeam4"));
        this.alreadyteam4 = ChatColor.translateAlternateColorCodes('&', this.language.getString("alreadyteam4"));
        this.team4full = ChatColor.translateAlternateColorCodes('&', this.language.getString("team4full"));
        this.jointeam5 = ChatColor.translateAlternateColorCodes('&', this.language.getString("jointeam5"));
        this.alreadyteam5 = ChatColor.translateAlternateColorCodes('&', this.language.getString("alreadyteam5"));
        this.team5full = ChatColor.translateAlternateColorCodes('&', this.language.getString("team5full"));
        this.jointeam6 = ChatColor.translateAlternateColorCodes('&', this.language.getString("jointeam6"));
        this.alreadyteam6 = ChatColor.translateAlternateColorCodes('&', this.language.getString("alreadyteam6"));
        this.team6full = ChatColor.translateAlternateColorCodes('&', this.language.getString("team6full"));
        this.jointeam7 = ChatColor.translateAlternateColorCodes('&', this.language.getString("jointeam7"));
        this.alreadyteam7 = ChatColor.translateAlternateColorCodes('&', this.language.getString("alreadyteam7"));
        this.team7full = ChatColor.translateAlternateColorCodes('&', this.language.getString("team7full"));
        this.jointeam8 = ChatColor.translateAlternateColorCodes('&', this.language.getString("jointeam8"));
        this.alreadyteam8 = ChatColor.translateAlternateColorCodes('&', this.language.getString("alreadyteam8"));
        this.team8full = ChatColor.translateAlternateColorCodes('&', this.language.getString("team8full"));
        this.jointeam9 = ChatColor.translateAlternateColorCodes('&', this.language.getString("jointeam9"));
        this.alreadyteam9 = ChatColor.translateAlternateColorCodes('&', this.language.getString("alreadyteam9"));
        this.team9full = ChatColor.translateAlternateColorCodes('&', this.language.getString("team9full"));
        this.TablistTeam1Colour = ChatColor.translateAlternateColorCodes('&', this.language.getString("TablistTeam1Colour"));
        this.TablistTeam2Colour = ChatColor.translateAlternateColorCodes('&', this.language.getString("TablistTeam2Colour"));
        this.TablistTeam3Colour = ChatColor.translateAlternateColorCodes('&', this.language.getString("TablistTeam3Colour"));
        this.TablistTeam4Colour = ChatColor.translateAlternateColorCodes('&', this.language.getString("TablistTeam4Colour"));
        this.TablistTeam5Colour = ChatColor.translateAlternateColorCodes('&', this.language.getString("TablistTeam5Colour"));
        this.TablistTeam6Colour = ChatColor.translateAlternateColorCodes('&', this.language.getString("TablistTeam6Colour"));
        this.TablistTeam7Colour = ChatColor.translateAlternateColorCodes('&', this.language.getString("TablistTeam7Colour"));
        this.TablistTeam8Colour = ChatColor.translateAlternateColorCodes('&', this.language.getString("TablistTeam8Colour"));
        this.TablistTeam9Colour = ChatColor.translateAlternateColorCodes('&', this.language.getString("TablistTeam9Colour"));
        this.TablistDefaultUserColour = ChatColor.translateAlternateColorCodes('&', this.language.getString("TablistDefaultUserColour"));
        this.TablistGamemasterColour = ChatColor.translateAlternateColorCodes('&', this.language.getString("TeablistGamemasterColour"));
        this.deathmessage = ChatColor.translateAlternateColorCodes('&', this.language.getString("deathmessage"));
        this.leftserveringame = ChatColor.translateAlternateColorCodes('&', this.language.getString("leftserveringame"));
        this.leftserveringamespectator = ChatColor.translateAlternateColorCodes('&', this.language.getString("leftserveringamespectator"));
        this.leftserverlobby = ChatColor.translateAlternateColorCodes('&', this.language.getString("leftserverlobby"));
        this.gameisrestarting = ChatColor.translateAlternateColorCodes('&', this.language.getString("gameisrestarting"));
        this.chatformatTeam1 = ChatColor.translateAlternateColorCodes('&', this.language.getString("chatformatTeam1"));
        this.chatformatTeam2 = ChatColor.translateAlternateColorCodes('&', this.language.getString("chatformatTeam2"));
        this.chatformatTeam3 = ChatColor.translateAlternateColorCodes('&', this.language.getString("chatformatTeam3"));
        this.chatformatTeam4 = ChatColor.translateAlternateColorCodes('&', this.language.getString("chatformatTeam4"));
        this.chatformatTeam5 = ChatColor.translateAlternateColorCodes('&', this.language.getString("chatformatTeam5"));
        this.chatformatTeam6 = ChatColor.translateAlternateColorCodes('&', this.language.getString("chatformatTeam6"));
        this.chatformatTeam7 = ChatColor.translateAlternateColorCodes('&', this.language.getString("chatformatTeam7"));
        this.chatformatTeam8 = ChatColor.translateAlternateColorCodes('&', this.language.getString("chatformatTeam8"));
        this.chatformatTeam9 = ChatColor.translateAlternateColorCodes('&', this.language.getString("chatformatTeam9"));
        this.chatformatwithoutteam = ChatColor.translateAlternateColorCodes('&', this.language.getString("chatformatwithoutteam"));
        this.chatcolourDefaultUser = ChatColor.translateAlternateColorCodes('&', this.language.getString("chatcolourDefaultUser"));
        this.chatcolourGamemaster = ChatColor.translateAlternateColorCodes('&', this.language.getString("chatcolourGamemaster"));
        this.scoreboardTitle = ChatColor.translateAlternateColorCodes('&', this.language.getString("scoreboardTitle"));
        this.scoreboardYourTeam = ChatColor.translateAlternateColorCodes('&', this.language.getString("scoreboardYourTeam"));
        this.scoreboardTeam1 = ChatColor.translateAlternateColorCodes('&', this.language.getString("scoreboardTeam1"));
        this.scoreboardTeam2 = ChatColor.translateAlternateColorCodes('&', this.language.getString("scoreboardTeam2"));
        this.scoreboardTeam3 = ChatColor.translateAlternateColorCodes('&', this.language.getString("scoreboardTeam3"));
        this.scoreboardTeam4 = ChatColor.translateAlternateColorCodes('&', this.language.getString("scoreboardTeam4"));
        this.scoreboardTeam5 = ChatColor.translateAlternateColorCodes('&', this.language.getString("scoreboardTeam5"));
        this.scoreboardTeam6 = ChatColor.translateAlternateColorCodes('&', this.language.getString("scoreboardTeam6"));
        this.scoreboardTeam7 = ChatColor.translateAlternateColorCodes('&', this.language.getString("scoreboardTeam7"));
        this.scoreboardTeam8 = ChatColor.translateAlternateColorCodes('&', this.language.getString("scoreboardTeam8"));
        this.scoreboardTeam9 = ChatColor.translateAlternateColorCodes('&', this.language.getString("scoreboardTeam9"));
        this.scoreboardNoTeam = ChatColor.translateAlternateColorCodes('&', this.language.getString("scoreboardNoTeam"));
        this.usagestart = ChatColor.translateAlternateColorCodes('&', this.language.getString("usagestart"));
        this.main = pl;
    }
}
